/**
 * QuickMeds Master Seed Dataset
 * File: server/src/seed/seedData.js
 */

const medicinesData = [
  {
    "name": "Telma 40mg Tablet",
    "genericName": "Telmisartan (40mg)",
    "brand": "Telma",
    "manufacturer": "Glenmark Pharmaceuticals Ltd",
    "strength": "40mg",
    "dosageForm": "Tablet",
    "category": "Cardiac & Diabetes",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H",
    "description": "Angiotensin receptor blocker used for hypertension control, heart failure management, and stroke prevention.",
    "usageInstructions": "Take 1 tablet daily with or without food at the same time each day.",
    "storage": "Store below 25°C away from direct sunlight.",
    "sideEffects": "Dizziness, back pain, sinus congestion in rare cases.",
    "mrp": 215,
    "image": "/medicines/telma-40mg-tablet.png"
  },
  {
    "name": "Ecosprin 75mg Tablet",
    "genericName": "Aspirin / Acetylsalicylic Acid (75mg)",
    "brand": "Ecosprin",
    "manufacturer": "USV Pvt Ltd",
    "strength": "75mg",
    "dosageForm": "Tablet",
    "category": "Cardiac & Diabetes",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H",
    "description": "Low-dose antiplatelet medication used to prevent blood clots, heart attacks, and secondary cardiovascular events.",
    "usageInstructions": "Take 1 tablet daily after meals with water.",
    "storage": "Store in a dry place below 30°C.",
    "sideEffects": "Mild dyspepsia, increased bleeding tendency.",
    "mrp": 5.5,
    "image": "/medicines/ecosprin-75mg-tablet.png"
  },
  {
    "name": "Sorbitrate 5mg Sublingual Tablet",
    "genericName": "Isosorbide Dinitrate (5mg)",
    "brand": "Sorbitrate",
    "manufacturer": "Abbott Healthcare Pvt Ltd",
    "strength": "5mg",
    "dosageForm": "Tablet",
    "category": "Cardiac & Diabetes",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H",
    "description": "Emergency sublingual vasodilator providing rapid relief from acute angina pectoris chest pain within 2-5 minutes.",
    "usageInstructions": "Dissolve 1 tablet under the tongue during sudden chest tightness or as prescribed.",
    "storage": "Keep in original amber glass bottle tightly closed below 25°C.",
    "sideEffects": "Throbbing headache, temporary dizziness, facial flushing.",
    "mrp": 38,
    "image": "/medicines/sorbitrate-5mg-sublingual-tablet.png"
  },
  {
    "name": "Atorva 20mg Tablet",
    "genericName": "Atorvastatin (20mg)",
    "brand": "Atorva",
    "manufacturer": "Zydus Healthcare",
    "strength": "20mg",
    "dosageForm": "Tablet",
    "category": "Cardiac & Diabetes",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H",
    "description": "Statin lipid-lowering agent reducing LDL cholesterol, triglycerides, and cardiovascular risk.",
    "usageInstructions": "Take 1 tablet at bedtime.",
    "storage": "Store below 25°C.",
    "sideEffects": "Muscle ache, elevated liver enzymes in rare cases.",
    "mrp": 185,
    "image": "/medicines/atorva-20mg-tablet.png"
  },
  {
    "name": "Asthalin 100mcg Inhaler",
    "genericName": "Salbutamol / Albuterol (100mcg/puff)",
    "brand": "Asthalin",
    "manufacturer": "Cipla Ltd",
    "strength": "200 Metered Doses",
    "dosageForm": "Inhaler",
    "category": "Cold & Cough",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H",
    "description": "Fast-acting emergency bronchodilator for rapid relief of acute asthma attacks, wheezing, and bronchospasm.",
    "usageInstructions": "Shake well before use. Inhale 1 to 2 puffs during sudden shortness of breath.",
    "storage": "Store below 30°C. Protect from frost and direct sunlight.",
    "sideEffects": "Mild tremor, tachycardia, transient headache.",
    "mrp": 162,
    "image": "/medicines/asthalin-100mcg-inhaler.png"
  },
  {
    "name": "Budecort 200mcg Inhaler",
    "genericName": "Budesonide (200mcg/puff)",
    "brand": "Budecort",
    "manufacturer": "Cipla Ltd",
    "strength": "200 Metered Doses",
    "dosageForm": "Inhaler",
    "category": "Cold & Cough",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H",
    "description": "Corticosteroid maintenance inhaler reducing airway inflammation in chronic asthma and COPD.",
    "usageInstructions": "Rinse mouth thoroughly with water after inhalation.",
    "storage": "Store below 25°C.",
    "sideEffects": "Oral candidiasis if mouth not rinsed, hoarseness.",
    "mrp": 340,
    "image": "/medicines/budecort-200mcg-inhaler.png"
  },
  {
    "name": "Ascoril D Plus Syrup (100ml)",
    "genericName": "Dextromethorphan (10mg) + Chlorpheniramine (2mg) + Phenylephrine (5mg)",
    "brand": "Ascoril",
    "manufacturer": "Glenmark Pharmaceuticals Ltd",
    "strength": "100ml",
    "dosageForm": "Syrup",
    "category": "Cold & Cough",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H",
    "description": "Triple active syrup for dry cough, allergic rhinitis, and upper respiratory tract congestion.",
    "usageInstructions": "Take 5-10ml two to three times daily after meals.",
    "storage": "Store at room temperature.",
    "mrp": 128,
    "image": "/medicines/ascoril-d-plus-syrup.png"
  },
  {
    "name": "Benadryl Cough Formula Syrup (150ml)",
    "genericName": "Diphenhydramine (14.08mg) + Ammonium Chloride (138mg)",
    "brand": "Benadryl",
    "manufacturer": "Johnson & Johnson Ltd",
    "strength": "150ml",
    "dosageForm": "Syrup",
    "category": "Cold & Cough",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Soothing expectorant syrup relieving chesty, tickly cough and sore throat irritation.",
    "mrp": 145,
    "image": "/medicines/benadryl-cough-formula-syrup.png"
  },
  {
    "name": "Otrivin Oxy Fast Relief Nasal Spray (10ml)",
    "genericName": "Oxymetazoline Hydrochloride (0.05% w/v)",
    "brand": "Otrivin",
    "manufacturer": "GSK Consumer Healthcare",
    "strength": "10ml",
    "dosageForm": "Drops",
    "category": "Cold & Cough",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Unblocks stuffy nasal passages within 25 seconds for up to 12 hours of clear breathing.",
    "mrp": 110,
    "image": "/medicines/otrivin-oxy-fast-relief-nasal-spray.png"
  },
  {
    "name": "Augmentin 625 Duo Tablet",
    "genericName": "Amoxicillin (500mg) + Clavulanic Acid (125mg)",
    "brand": "Augmentin",
    "manufacturer": "GlaxoSmithKline Pharmaceuticals Ltd",
    "strength": "625mg",
    "dosageForm": "Tablet",
    "category": "Antibiotics & Anti-infectives",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H1",
    "description": "Broad-spectrum antibiotic for bacterial respiratory tract, ENT, skin, and soft tissue infections.",
    "usageInstructions": "Take 1 tablet twice daily with meals to optimize absorption and reduce GI distress.",
    "storage": "Store in moisture-proof packaging below 25°C.",
    "sideEffects": "Mild diarrhea, nausea, skin rash.",
    "mrp": 204,
    "image": "/medicines/augmentin-625-duo-tablet.png"
  },
  {
    "name": "Azithral 500mg Tablet",
    "genericName": "Azithromycin (500mg)",
    "brand": "Azithral",
    "manufacturer": "Alembic Pharmaceuticals Ltd",
    "strength": "500mg",
    "dosageForm": "Tablet",
    "category": "Antibiotics & Anti-infectives",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H1",
    "description": "Macrolide antibiotic treating tonsillitis, sinus infections, community-acquired pneumonia, and bronchitis.",
    "usageInstructions": "Take 1 tablet daily 1 hour before or 2 hours after meals for 3-5 days.",
    "storage": "Store below 30°C.",
    "mrp": 132,
    "image": "/medicines/azithral-500mg-tablet.png"
  },
  {
    "name": "Ciplox 500mg Tablet",
    "genericName": "Ciprofloxacin (500mg)",
    "brand": "Ciplox",
    "manufacturer": "Cipla Ltd",
    "strength": "500mg",
    "dosageForm": "Tablet",
    "category": "Antibiotics & Anti-infectives",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H1",
    "description": "Fluoroquinolone antibiotic for urinary tract, gastrointestinal, and systemic bacterial infections.",
    "mrp": 48,
    "image": "/medicines/ciplox-500mg-tablet.png"
  },
  {
    "name": "Taxim-O 200mg Tablet",
    "genericName": "Cefixime (200mg)",
    "brand": "Taxim-O",
    "manufacturer": "Alkem Laboratories Ltd",
    "strength": "200mg",
    "dosageForm": "Tablet",
    "category": "Antibiotics & Anti-infectives",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H1",
    "description": "Third-generation cephalosporin antibiotic for typhoid, UTI, otitis media, and bronchitis.",
    "mrp": 175,
    "image": "/medicines/taxim-o-200mg-tablet.png"
  },
  {
    "name": "Dolo 650mg Tablet",
    "genericName": "Paracetamol (650mg)",
    "brand": "Dolo",
    "manufacturer": "Micro Labs Ltd",
    "strength": "650mg",
    "dosageForm": "Tablet",
    "category": "Fever & Pain",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "High-efficacy analgesic and antipyretic medicine for fever reduction, dental pain, body ache, and headache.",
    "usageInstructions": "Take 1 tablet every 4-6 hours as needed. Do not exceed 4 tablets in 24 hours.",
    "storage": "Store below 30°C in a dry place.",
    "mrp": 34,
    "image": "/medicines/dolo-650mg-tablet.png",
    "sosEligible": true,
    "sosCategory": "COMFORT_RELIEF"
  },
  {
    "name": "Crocin 500 Advance Tablet",
    "genericName": "Paracetamol (500mg) with Optizorb",
    "brand": "Crocin",
    "manufacturer": "GlaxoSmithKline Pharmaceuticals Ltd",
    "strength": "500mg",
    "dosageForm": "Tablet",
    "category": "Fever & Pain",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Fast-acting paracetamol with rapid disintegration technology for prompt headache and fever relief.",
    "mrp": 22.5,
    "image": "/medicines/crocin-500-advance-tablet.png"
  },
  {
    "name": "Combiflam Tablet",
    "genericName": "Ibuprofen (400mg) + Paracetamol (325mg)",
    "brand": "Combiflam",
    "manufacturer": "Sanofi India Ltd",
    "strength": "400mg + 325mg",
    "dosageForm": "Tablet",
    "category": "Fever & Pain",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H",
    "description": "Dual anti-inflammatory and analgesic combination for muscle pain, dental ache, joint sprains, and fever.",
    "usageInstructions": "Always take with food or milk to prevent gastric irritation.",
    "mrp": 45,
    "image": "/medicines/combiflam-tablet.png",
    "sosEligible": true,
    "sosCategory": "COMFORT_RELIEF"
  },
  {
    "name": "Meftal Spas Tablet",
    "genericName": "Mefenamic Acid (250mg) + Dicyclomine (10mg)",
    "brand": "Meftal",
    "manufacturer": "Blue Cross Laboratories Ltd",
    "strength": "250mg + 10mg",
    "dosageForm": "Tablet",
    "category": "Fever & Pain",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H",
    "description": "Relieves spasmodic abdominal cramps, intestinal colic, and menstrual pain.",
    "mrp": 52,
    "image": "/medicines/meftal-spas-tablet.png"
  },
  {
    "name": "Saridon Headache Relief Tablet",
    "genericName": "Paracetamol (250mg) + Propyphenazone (150mg) + Caffeine (50mg)",
    "brand": "Saridon",
    "manufacturer": "Piramal Pharma Ltd",
    "strength": "Triple Action",
    "dosageForm": "Tablet",
    "category": "Fever & Pain",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Classic triple-action formula providing rapid relief from acute tension headaches and toothaches within 30 minutes.",
    "mrp": 42,
    "image": "/medicines/saridon-headache-relief-tablet.png"
  },
  {
    "name": "Volini Pain Relief Gel (50g)",
    "genericName": "Diclofenac Diethylamine + Virgin Linseed Oil + Methyl Salicylate + Menthol",
    "brand": "Volini",
    "manufacturer": "Sun Pharmaceutical Industries Ltd",
    "strength": "50g",
    "dosageForm": "Gel",
    "category": "Fever & Pain",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Deep penetrating pain relief gel for neck pain, lower backache, joint stiffness, and athletic sprains.",
    "mrp": 165,
    "image": "/medicines/volini-pain-relief-gel.png"
  },
  {
    "name": "Glycomet-GP 1 Tablet",
    "genericName": "Glimepiride (1mg) + Metformin (500mg SR)",
    "brand": "Glycomet",
    "manufacturer": "USV Pvt Ltd",
    "strength": "1mg + 500mg",
    "dosageForm": "Tablet",
    "category": "Cardiac & Diabetes",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H",
    "description": "Dual antidiabetic therapy controlling blood glucose levels in Type-2 Diabetes Mellitus.",
    "usageInstructions": "Take 1 tablet daily with breakfast.",
    "storage": "Store below 25°C.",
    "sideEffects": "Hypoglycemia if meals skipped, mild metallic taste.",
    "mrp": 125,
    "image": "/medicines/glycomet-gp-1-tablet.png"
  },
  {
    "name": "Janumet 50mg/500mg Tablet",
    "genericName": "Sitagliptin (50mg) + Metformin (500mg)",
    "brand": "Janumet",
    "manufacturer": "MSD Pharmaceuticals Pvt Ltd",
    "strength": "50mg + 500mg",
    "dosageForm": "Tablet",
    "category": "Cardiac & Diabetes",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H",
    "description": "DPP-4 inhibitor combined with metformin providing steady glycemic control with low hypoglycemic risk.",
    "mrp": 380,
    "image": "/medicines/janumet-50mg-500mg-tablet.png"
  },
  {
    "name": "Human Mixtard 30/70 100IU/ml Injection",
    "genericName": "Biphasic Isophane Insulin (30% Soluble / 70% Isophane)",
    "brand": "Mixtard",
    "manufacturer": "Novo Nordisk India Pvt Ltd",
    "strength": "10ml Vial (1000 IU)",
    "dosageForm": "Injection",
    "category": "Cardiac & Diabetes",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H",
    "description": "Emergency and maintenance insulin maintaining basal and prandial glycemic control in diabetes patients.",
    "usageInstructions": "Administer subcutaneously 30 minutes before meal as directed by endocrinologist.",
    "storage": "Store in refrigerator (2°C - 8°C). Do not freeze.",
    "sideEffects": "Hypoglycemia, injection site lipodystrophy.",
    "mrp": 195,
    "image": "/medicines/human-mixtard-30-70-injection.png"
  },
  {
    "name": "Calpol 250mg Peadiatric Suspension (60ml)",
    "genericName": "Paracetamol (250mg / 5ml)",
    "brand": "Calpol",
    "manufacturer": "GlaxoSmithKline Pharmaceuticals Ltd",
    "strength": "60ml Bottle",
    "dosageForm": "Suspension",
    "category": "Fever & Pain",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Strawberry-flavoured pediatric paracetamol suspension for rapid fever and pain relief in infants and children.",
    "usageInstructions": "Dosage based on child body weight. Use measuring cap provided.",
    "storage": "Store below 25°C away from direct sunlight.",
    "mrp": 45,
    "image": "/medicines/calpol-250mg-paediatric-suspension.png"
  },
  {
    "name": "Maxtra Oral Drops (15ml)",
    "genericName": "Phenylephrine (2.5mg) + Chlorpheniramine (1mg/ml)",
    "brand": "Maxtra",
    "manufacturer": "Zuventus Healthcare Ltd",
    "strength": "15ml with Dropper",
    "dosageForm": "Drops",
    "category": "Cold & Cough",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H",
    "description": "Pediatric cold and nasal decongestant drops relieving blocked nose, sneezing, and runny nose in children.",
    "mrp": 78,
    "image": "/medicines/maxtra-oral-drops.png"
  },
  {
    "name": "Ondem Syrup (30ml)",
    "genericName": "Ondansetron (2mg / 5ml)",
    "brand": "Ondem",
    "manufacturer": "Alkem Laboratories Ltd",
    "strength": "30ml",
    "dosageForm": "Syrup",
    "category": "Digestive Care",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H",
    "description": "Pediatric antiemetic medication stopping sudden acute vomiting, gastroenteritis, and nausea in children.",
    "usageInstructions": "Administer 30 mins before feeding or medication as directed by pediatrician.",
    "mrp": 42,
    "image": "/medicines/ondem-syrup.png"
  },
  {
    "name": "Pan-D Capsule",
    "genericName": "Pantoprazole (40mg) + Domperidone (30mg SR)",
    "brand": "Pan",
    "manufacturer": "Alkem Laboratories Ltd",
    "strength": "40mg + 30mg",
    "dosageForm": "Capsule",
    "category": "Digestive Care",
    "requiresPrescription": true,
    "prescriptionSchedule": "Schedule H",
    "description": "Proton-pump inhibitor and prokinetic treating severe acid reflux (GERD), heartburn, gastric fullness, and nausea.",
    "usageInstructions": "Take 1 capsule on an empty stomach in the morning 30 minutes before breakfast.",
    "mrp": 199,
    "image": "/medicines/pan-d-capsule.png"
  },
  {
    "name": "Digene Acidity Relief Gel Mint (200ml)",
    "genericName": "Magnesium Hydroxide + Aluminium Hydroxide + Simethicone",
    "brand": "Digene",
    "manufacturer": "Abbott Healthcare Pvt Ltd",
    "strength": "200ml",
    "dosageForm": "Suspension",
    "category": "Digestive Care",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Sugar-free, scientifically balanced antacid gel providing instant soothing relief from acidity and gas.",
    "mrp": 168,
    "image": "/medicines/digene-acidity-relief-gel-mint.png"
  },
  {
    "name": "Electral ORS Powder (21.8g Sachet)",
    "genericName": "WHO Recommended Oral Rehydration Salts Formula",
    "brand": "Electral",
    "manufacturer": "FDC Ltd",
    "strength": "21.8g",
    "dosageForm": "Powder",
    "category": "Digestive Care",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Restores essential body electrolytes and fluids lost during acute dehydration, diarrhea, heat exhaustion, and vomiting.",
    "usageInstructions": "Dissolve entire sachet in 1 Litre of clean drinking water. Consume within 24 hours.",
    "mrp": 22,
    "image": "/medicines/electral-ors-powder.png",
    "sosEligible": true,
    "sosCategory": "COMFORT_RELIEF"
  },
  {
    "name": "Betadine 10% Microbicidal Ointment (20g)",
    "genericName": "Povidone Iodine (10% w/w)",
    "brand": "Betadine",
    "manufacturer": "Win-Medicare Pvt Ltd",
    "strength": "20g",
    "dosageForm": "Ointment",
    "category": "First Aid & Surgical",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Broad-spectrum antiseptic ointment for treating cuts, burns, scrapes, and preventing bacterial/fungal wound infections.",
    "mrp": 120,
    "image": "/medicines/betadine-10-microbicidal-ointment.png"
  },
  {
    "name": "Dettol Antiseptic Liquid (250ml)",
    "genericName": "Chloroxylenol (4.8% w/v)",
    "brand": "Dettol",
    "manufacturer": "Reckitt Benckiser India Ltd",
    "strength": "250ml",
    "dosageForm": "Bottle",
    "category": "First Aid & Surgical",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Gold-standard antiseptic disinfectant for wound cleaning, emergency first aid, and surgical hygiene.",
    "mrp": 154,
    "image": "/medicines/dettol-antiseptic-liquid.png"
  },
  {
    "name": "Hansaplast Regular Bandage Strips (Pack of 20)",
    "genericName": "Sterile Adhesive Medicated Bandages",
    "brand": "Hansaplast",
    "manufacturer": "Beiersdorf India Pvt Ltd",
    "strength": "20 Strips",
    "dosageForm": "Strip",
    "category": "First Aid & Surgical",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Breathable, antiseptic wound plaster protecting everyday cuts and scrapes from dirt and bacteria.",
    "mrp": 45,
    "image": "/medicines/hansaplast-regular-bandage-strips.png"
  },
  {
    "name": "Whisper Ultra Clean Sanitary Pads XL (30 Pads)",
    "genericName": "Sanitary Napkin with Wings XL",
    "brand": "Whisper",
    "manufacturer": "Procter & Gamble Hygiene and Health Care Ltd",
    "strength": "XL - 30 Pads",
    "dosageForm": "Device",
    "category": "Women Care & Hygiene",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Ultra-absorbent wings design with 1000 suction holes for up to 12 hours of leak-lock menstrual hygiene.",
    "mrp": 329,
    "image": "/medicines/whisper-ultra-clean-sanitary-pads.png"
  },
  {
    "name": "VWash Plus Intimate Hygiene Wash (200ml)",
    "genericName": "Lactic Acid + Tea Tree Oil Wash",
    "brand": "VWash",
    "manufacturer": "Glenmark Pharmaceuticals Ltd",
    "strength": "200ml",
    "dosageForm": "Bottle",
    "category": "Women Care & Hygiene",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Maintains optimal vaginal pH 3.5 to prevent irritation, bacterial vaginosis, and odour.",
    "mrp": 225,
    "image": "/medicines/vwash-plus-intimate-hygiene-wash.png",
    "sosEligible": true,
    "sosCategory": "HYGIENE_ESSENTIALS"
  },
  {
    "name": "Limcee 500mg Chewable Tablet",
    "genericName": "Vitamin C / Ascorbic Acid (500mg)",
    "brand": "Limcee",
    "manufacturer": "Abbott Healthcare Pvt Ltd",
    "strength": "500mg",
    "dosageForm": "Chewable Tablet",
    "category": "Vitamins & Supplements",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Immunity booster and antioxidant vitamin C chewable tablet with orange flavour for daily wellness.",
    "usageInstructions": "Chew 1 tablet daily or as directed by physician.",
    "storage": "Store in a cool dry place below 25°C.",
    "sideEffects": "None reported with standard dosage.",
    "mrp": 28,
    "image": "/medicines/limcee-500mg-chewable-tablet.png"
  },
  {
    "name": "Shelcal 500 Tablet",
    "genericName": "Calcium (500mg) + Vitamin D3 (250 IU)",
    "brand": "Shelcal",
    "manufacturer": "Torrent Pharmaceuticals Ltd",
    "strength": "500mg + 250IU",
    "dosageForm": "Tablet",
    "category": "Vitamins & Supplements",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Essential calcium and vitamin D3 supplement for bone strength, joint mobility, and calcium deficiency.",
    "usageInstructions": "Take 1 tablet daily after meals with water.",
    "storage": "Store protected from light and moisture below 30°C.",
    "sideEffects": "Mild constipation if taken without sufficient water.",
    "mrp": 135,
    "image": "/medicines/shelcal-500-tablet.png"
  },
  {
    "name": "Becosules Z Capsule",
    "genericName": "B-Complex Forte + Vitamin C + Zinc",
    "brand": "Becosules",
    "manufacturer": "Pfizer Ltd",
    "strength": "Standard Forte",
    "dosageForm": "Capsule",
    "category": "Vitamins & Supplements",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Therapeutic vitamin B-complex with zinc and vitamin C for tissue repair, mouth ulcers, and energy vitality.",
    "usageInstructions": "Take 1 capsule daily after breakfast.",
    "storage": "Store in a dry place below 25°C.",
    "sideEffects": "Mild bright yellow discoloration of urine (harmless B2 excretion).",
    "mrp": 52,
    "image": "/medicines/becosules-z-capsule.png"
  },
  {
    "name": "Sanitary Pads – Regular (Whisper Choice)",
    "genericName": "Sanitary Napkins Regular Flow (6 Pads)",
    "brand": "Whisper Choice",
    "manufacturer": "Procter & Gamble Hygiene and Health Care Ltd",
    "strength": "6 Regular Pads",
    "dosageForm": "Pads",
    "category": "Women Care & Hygiene",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Soft cottony cover sanitary napkins designed for comfort and leak protection during regular flow.",
    "mrp": 35,
    "image": "/medicines/whisper-choice-regular-pads.svg",
    "sosEligible": true,
    "sosCategory": "MENSTRUAL_CARE"
  },
  {
    "name": "Sanitary Pads – XL (Whisper Ultra Clean)",
    "genericName": "Sanitary Napkins Heavy Flow XL (15 Pads)",
    "brand": "Whisper Ultra",
    "manufacturer": "Procter & Gamble Hygiene and Health Care Ltd",
    "strength": "15 XL Pads",
    "dosageForm": "Pads",
    "category": "Women Care & Hygiene",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Extra-long sanitary napkins with 360-degree leakage protection and odour lock gel technology.",
    "mrp": 140,
    "image": "/medicines/whisper-ultra-xl-pads.svg",
    "sosEligible": true,
    "sosCategory": "MENSTRUAL_CARE"
  },
  {
    "name": "Tampons (O.B. ProComfort Regular)",
    "genericName": "Absorbent Cotton Tampons Regular (10 Tampons)",
    "brand": "O.B.",
    "manufacturer": "Johnson & Johnson Consumer Inc",
    "strength": "10 Regular Tampons",
    "dosageForm": "Tampon",
    "category": "Women Care & Hygiene",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "FluidLock grooves and SilkTouch cover for smooth insertion and reliable leak protection.",
    "mrp": 195,
    "image": "/medicines/ob-tampons-regular.svg",
    "sosEligible": true,
    "sosCategory": "MENSTRUAL_CARE"
  },
  {
    "name": "Menstrual Cup (Sirona Reusable Medium)",
    "genericName": "Medical-Grade Silicone Reusable Menstrual Cup",
    "brand": "Sirona",
    "manufacturer": "Sirona Hygiene Pvt Ltd",
    "strength": "Medium (1 Unit)",
    "dosageForm": "Cup",
    "category": "Women Care & Hygiene",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Eco-friendly, 100% medical-grade silicone cup providing up to 8-12 hours of leakproof protection.",
    "mrp": 299,
    "image": "/medicines/sirona-menstrual-cup.svg",
    "sosEligible": true,
    "sosCategory": "MENSTRUAL_CARE"
  },
  {
    "name": "Heating Pad / Hot Water Bottle (Flamingo)",
    "genericName": "Electric Heating Pad for Cramp & Pain Relief",
    "brand": "Flamingo",
    "manufacturer": "Ascent Meditech Ltd",
    "strength": "1 Unit (Electric)",
    "dosageForm": "Device",
    "category": "Pain Relief",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Thermostatically controlled electric heating pad providing targeted warmth for menstrual cramp and muscle relief.",
    "mrp": 350,
    "image": "/medicines/flamingo-heating-pad.svg",
    "sosEligible": true,
    "sosCategory": "COMFORT_RELIEF"
  },
  {
    "name": "Heat Patch (Nua Cramp Comfort 3 Patches)",
    "genericName": "Air-Activated Cramp Comfort Heat Patches",
    "brand": "Nua",
    "manufacturer": "Lagom Labs Pvt Ltd",
    "strength": "3 Self-Heating Patches",
    "dosageForm": "Patch",
    "category": "Pain Relief",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Natural air-activated heating patches providing soothing 8-hour heat therapy for abdominal cramps.",
    "mrp": 199,
    "image": "/medicines/nua-heat-patch.svg",
    "sosEligible": true,
    "sosCategory": "COMFORT_RELIEF"
  },
  {
    "name": "Unscented Wet Wipes (Himalaya Gentle 72s)",
    "genericName": "Aloe Vera & Lotus Unscented Cleansing Wipes",
    "brand": "Himalaya",
    "manufacturer": "Himalaya Wellness Company",
    "strength": "72 Pack",
    "dosageForm": "Wipes",
    "category": "Skin & Personal Care",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Alcohol-free, unscented gentle cleansing wet wipes enriched with Aloe Vera and Lotus extracts.",
    "mrp": 125,
    "image": "/medicines/himalaya-wet-wipes.svg",
    "sosEligible": true,
    "sosCategory": "HYGIENE_ESSENTIALS"
  },
  {
    "name": "Tissues (Paseo Soft Facial Tissue Box)",
    "genericName": "2-Ply Soft Facial Tissues (100 Sheets)",
    "brand": "Paseo",
    "manufacturer": "APP India Tissue Pvt Ltd",
    "strength": "100 Sheets",
    "dosageForm": "Tissues",
    "category": "Skin & Personal Care",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Ultra-soft, 100% virgin pulp 2-ply facial tissues for hygienic daily comfort.",
    "mrp": 85,
    "image": "/medicines/paseo-facial-tissues.svg",
    "sosEligible": true,
    "sosCategory": "HYGIENE_ESSENTIALS"
  },
  {
    "name": "Disposable Sanitary-Waste Bags (Sirona 15s)",
    "genericName": "Oxo-Biodegradable Sanitary Disposal Bags",
    "brand": "Sirona",
    "manufacturer": "Sirona Hygiene Pvt Ltd",
    "strength": "15 Bags",
    "dosageForm": "Bags",
    "category": "Women Care & Hygiene",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Tamper-proof, odour-concealing oxo-biodegradable bags for hygienic disposal of sanitary products.",
    "mrp": 99,
    "image": "/medicines/sirona-disposal-bags.svg",
    "sosEligible": true,
    "sosCategory": "HYGIENE_ESSENTIALS"
  },
  {
    "name": "Hand Sanitizer (Dettol Instant 100ml)",
    "genericName": "Alcohol Hand Rub Sanitizer Gel (70% Alcohol)",
    "brand": "Dettol",
    "manufacturer": "Reckitt Benckiser India Ltd",
    "strength": "100ml",
    "dosageForm": "Bottle",
    "category": "Skin & Personal Care",
    "requiresPrescription": false,
    "prescriptionSchedule": "OTC",
    "description": "Rinse-free instant hand sanitizer gel killing 99.99% of germs without water.",
    "mrp": 50,
    "image": "/medicines/dettol-hand-sanitizer.svg",
    "sosEligible": true,
    "sosCategory": "HYGIENE_ESSENTIALS"
  }
];

const pharmaciesData = [
  {
    "name": "Apollo Pharmacy — Connaught Place",
    "tagline": "24x7 Central Dispense Superstore & Rapid Hub",
    "phone": "+91 98110 23456",
    "email": "apollo@pharmacy.in",
    "licenseNumber": "DL-ND-2023-99881",
    "verificationStatus": "VERIFIED",
    "rating": 4.8,
    "totalRatings": 342,
    "totalOrdersCompleted": 850,
    "deliveryAvailable": true,
    "isOpen": true,
    "serviceRadiusKm": 15,
    "operatingHours": {
      "open": "00:00 AM",
      "close": "11:59 PM",
      "is24x7": true,
      "isOpenToday": true
    },
    "address": {
      "street": "Block E, Inner Circle, Connaught Place",
      "city": "New Delhi",
      "state": "Delhi",
      "pincode": "110001",
      "landmark": "Near Rajiv Chowk Metro Gate 5",
      "fullAddress": "Block E, Inner Circle, Connaught Place, New Delhi 110001"
    },
    "location": {
      "type": "Point",
      "coordinates": [
        77.2195,
        28.6328
      ]
    }
  },
  {
    "name": "MedPlus Chemist & Druggist — Karol Bagh",
    "tagline": "Genuine Prescription Medicines & Express Packing",
    "phone": "+91 98112 34567",
    "email": "medplus@pharmacy.in",
    "licenseNumber": "DL-ND-2023-77662",
    "verificationStatus": "VERIFIED",
    "rating": 4.6,
    "totalRatings": 218,
    "totalOrdersCompleted": 540,
    "deliveryAvailable": true,
    "isOpen": true,
    "serviceRadiusKm": 12,
    "operatingHours": {
      "open": "07:30 AM",
      "close": "11:30 PM",
      "is24x7": false,
      "isOpenToday": true
    },
    "address": {
      "street": "Arya Samaj Road, Karol Bagh",
      "city": "New Delhi",
      "state": "Delhi",
      "pincode": "110005",
      "landmark": "Opposite Gaffar Market",
      "fullAddress": "14/2 Arya Samaj Road, Karol Bagh, New Delhi 110005"
    },
    "location": {
      "type": "Point",
      "coordinates": [
        77.1906,
        28.6514
      ]
    }
  },
  {
    "name": "Guardian Health & Beauty — South Extension",
    "tagline": "Emergency Care Specialist & Critical Medicine Inventory",
    "phone": "+91 98114 56789",
    "email": "guardian@pharmacy.in",
    "licenseNumber": "DL-SD-2022-55443",
    "verificationStatus": "VERIFIED",
    "rating": 4.7,
    "totalRatings": 184,
    "totalOrdersCompleted": 420,
    "deliveryAvailable": true,
    "isOpen": true,
    "serviceRadiusKm": 12,
    "operatingHours": {
      "open": "08:00 AM",
      "close": "11:00 PM",
      "is24x7": false,
      "isOpenToday": true
    },
    "address": {
      "street": "Part 2 Main Market, South Extension",
      "city": "New Delhi",
      "state": "Delhi",
      "pincode": "110049",
      "landmark": "Near AIIMS Metro Flyover",
      "fullAddress": "F-22, South Extension Part 2, New Delhi 110049"
    },
    "location": {
      "type": "Point",
      "coordinates": [
        77.2215,
        28.5714
      ]
    }
  },
  {
    "name": "Netmeds Hyperlocal Pharmacy — Lajpat Nagar",
    "tagline": "Verified Pharmacists on Duty & Fast Dispatch Unit",
    "phone": "+91 98116 78901",
    "email": "netmeds@pharmacy.in",
    "licenseNumber": "DL-SD-2024-33221",
    "verificationStatus": "VERIFIED",
    "rating": 4.5,
    "totalRatings": 146,
    "totalOrdersCompleted": 310,
    "deliveryAvailable": true,
    "isOpen": true,
    "serviceRadiusKm": 10,
    "operatingHours": {
      "open": "08:00 AM",
      "close": "11:00 PM",
      "is24x7": false,
      "isOpenToday": true
    },
    "address": {
      "street": "Central Market, Lajpat Nagar II",
      "city": "New Delhi",
      "state": "Delhi",
      "pincode": "110024",
      "landmark": "Near 3Cs Cinema Complex",
      "fullAddress": "M-18, Central Market, Lajpat Nagar II, New Delhi 110024"
    },
    "location": {
      "type": "Point",
      "coordinates": [
        77.2433,
        28.5677
      ]
    }
  },
  {
    "name": "Fortis Health Pharmacy — Vasant Kunj",
    "tagline": "Hospital Affiliated 24x7 Emergency Med Dispensary",
    "phone": "+91 98117 88990",
    "email": "fortis@pharmacy.in",
    "licenseNumber": "DL-SW-2023-88771",
    "verificationStatus": "VERIFIED",
    "rating": 4.9,
    "totalRatings": 260,
    "totalOrdersCompleted": 680,
    "deliveryAvailable": true,
    "isOpen": true,
    "serviceRadiusKm": 15,
    "operatingHours": {
      "open": "00:00 AM",
      "close": "11:59 PM",
      "is24x7": true,
      "isOpenToday": true
    },
    "address": {
      "street": "Sector B, Pocket 1, Aruna Asaf Ali Marg, Vasant Kunj",
      "city": "New Delhi",
      "state": "Delhi",
      "pincode": "110070",
      "landmark": "Near Fortis Flt Lt Rajan Dhall Hospital",
      "fullAddress": "Sector B, Pocket 1, Vasant Kunj, New Delhi 110070"
    },
    "location": {
      "type": "Point",
      "coordinates": [
        77.155,
        28.5244
      ]
    }
  },
  {
    "name": "Wellness Forever Chemist — Janakpuri",
    "tagline": "Certified Retail Chemist & 24-Hour Emergency Dispenser",
    "phone": "+91 98118 90123",
    "email": "wellness@pharmacy.in",
    "licenseNumber": "DL-WD-2024-11009",
    "verificationStatus": "VERIFIED",
    "rating": 4.6,
    "totalRatings": 135,
    "totalOrdersCompleted": 275,
    "deliveryAvailable": true,
    "isOpen": true,
    "serviceRadiusKm": 10,
    "operatingHours": {
      "open": "00:00 AM",
      "close": "11:59 PM",
      "is24x7": true,
      "isOpenToday": true
    },
    "address": {
      "street": "District Centre, Janakpuri",
      "city": "New Delhi",
      "state": "Delhi",
      "pincode": "110058",
      "landmark": "Near Piccadily Hotel Complex",
      "fullAddress": "Shop 4, District Centre, Janakpuri, New Delhi 110058"
    },
    "location": {
      "type": "Point",
      "coordinates": [
        77.0854,
        28.6297
      ]
    }
  },
  {
    "name": "Max Life Chemist — Dwarka Sector 10",
    "tagline": "New Registration (Pending Compliance Verification)",
    "phone": "+91 98119 45678",
    "email": "maxlife@pharmacy.in",
    "licenseNumber": "DL-SW-2026-66432",
    "verificationStatus": "PENDING",
    "verificationNotes": "Drug retail licence certificate submitted. Under audit review.",
    "rating": 4.2,
    "totalRatings": 12,
    "totalOrdersCompleted": 15,
    "deliveryAvailable": true,
    "isOpen": true,
    "serviceRadiusKm": 8,
    "operatingHours": {
      "open": "08:00 AM",
      "close": "10:30 PM",
      "is24x7": false,
      "isOpenToday": true
    },
    "address": {
      "street": "Plot 12, Central Plaza, Sector 10, Dwarka",
      "city": "New Delhi",
      "state": "Delhi",
      "pincode": "110075",
      "landmark": "Opposite Dwarka Sector 10 Metro Station",
      "fullAddress": "Plot 12, Sector 10, Dwarka, New Delhi 110075"
    },
    "location": {
      "type": "Point",
      "coordinates": [
        77.0573,
        28.5813
      ]
    }
  }
];

module.exports = {
  medicinesData,
  pharmaciesData
};
