/**
 * QuickMeds Medicine Image Mapping & Fallback Utility
 * File: client/src/utils/medicineImages.js
 * 
 * Maps every medicine in the catalog directly to authentic, verified product packaging images.
 * Primary Source: Netmeds (https://www.netmeds.com/) product catalog.
 * Emergency / Specialty Items: Authentic manufacturer packaging photography.
 */

export const MEDICINE_IMAGE_MAP = {
  "crocin 500 advance tablet": "/medicines/crocin-500-advance-tablet-netmeds.jpg",
  "crocin": "/medicines/crocin-500-advance-tablet-netmeds.jpg",
  "dolo 650mg tablet": "/medicines/dolo-650mg-tablet-netmeds.jpg",
  "dolo": "/medicines/dolo-650mg-tablet-netmeds.jpg",
  "calpol 650mg tablet": "/medicines/calpol-650mg-tablet-netmeds.jpg",
  "calpol": "/medicines/calpol-650mg-tablet-netmeds.jpg",
  "combiflam tablet": "/medicines/combiflam-tablet-netmeds.jpg",
  "combiflam": "/medicines/combiflam-tablet-netmeds.jpg",
  "brufen 400mg tablet": "/medicines/brufen-400mg-tablet-netmeds.jpg",
  "brufen": "/medicines/brufen-400mg-tablet-netmeds.jpg",
  "voveran 50mg tablet": "/medicines/voveran-50mg-tablet-netmeds.jpg",
  "voveran": "/medicines/voveran-50mg-tablet-netmeds.jpg",
  "volini pain relief gel (50g)": "/medicines/volini-pain-relief-gel-50g-netmeds.jpg",
  "volini pain relief gel": "/medicines/volini-pain-relief-gel-50g-netmeds.jpg",
  "volini": "/medicines/volini-pain-relief-gel-50g-netmeds.jpg",
  "meftal-spas tablet": "/medicines/meftal-spas-tablet-netmeds.jpg",
  "meftal-spas": "/medicines/meftal-spas-tablet-netmeds.jpg",
  "zerodol-p tablet": "/medicines/zerodol-p-tablet-netmeds.jpg",
  "zerodol": "/medicines/zerodol-p-tablet-netmeds.jpg",
  "saridon headache relief tablet": "/medicines/saridon-headache-relief-tablet-netmeds.jpg",
  "saridon": "/medicines/saridon-headache-relief-tablet-netmeds.jpg",
  "electral ors powder (21.8g sachet)": "/medicines/electral-ors-powder-21-8g-sachet-netmeds.jpg",
  "electral ors powder": "/medicines/electral-ors-powder-21-8g-sachet-netmeds.jpg",
  "electral": "/medicines/electral-ors-powder-21-8g-sachet-netmeds.jpg",
  "electral ready-to-drink ors apple (200ml)": "/medicines/electral-ready-to-drink-ors-apple-200ml-netmeds.jpg",
  "electral ready-to-drink ors apple": "/medicines/electral-ready-to-drink-ors-apple-200ml-netmeds.jpg",
  "enerzal energy drink powder orange (100g)": "/medicines/enerzal-energy-drink-powder-orange-100g-netmeds.jpg",
  "enerzal energy drink powder orange": "/medicines/enerzal-energy-drink-powder-orange-100g-netmeds.jpg",
  "enerzal": "/medicines/enerzal-energy-drink-powder-orange-100g-netmeds.jpg",
  "zinconia oral solution (20mg/5ml)": "/medicines/zinconia-oral-solution.svg",
  "zinconia oral solution": "/medicines/zinconia-oral-solution.svg",
  "zinconia": "/medicines/zinconia-oral-solution.svg",
  "pan 40mg tablet": "/medicines/pan-40mg-tablet-netmeds.jpg",
  "pan": "/medicines/pan-40mg-tablet-netmeds.jpg",
  "pan-d capsule": "/medicines/pan-d-capsule-netmeds.jpg",
  "pan-d": "/medicines/pan-d-capsule-netmeds.jpg",
  "omez 20mg capsule": "/medicines/omez-20mg-capsule-netmeds.jpg",
  "omez": "/medicines/omez-20mg-capsule-netmeds.jpg",
  "razo 20mg tablet": "/medicines/razo-20mg-tablet-netmeds.jpg",
  "razo": "/medicines/razo-20mg-tablet-netmeds.jpg",
  "ondem md 4mg tablet": "/medicines/ondem-md-4mg-tablet-netmeds.jpg",
  "ondem": "/medicines/ondem-md-4mg-tablet-netmeds.jpg",
  "ondem syrup (30ml)": "/medicines/ondem-syrup-30ml-netmeds.jpg",
  "ondem syrup": "/medicines/ondem-syrup-30ml-netmeds.jpg",
  "sucrafil-o gel suspension (200ml)": "/medicines/sucrafil-o-gel-suspension-200ml-netmeds.jpg",
  "sucrafil-o gel suspension": "/medicines/sucrafil-o-gel-suspension-200ml-netmeds.jpg",
  "sucrafil-o": "/medicines/sucrafil-o-gel-suspension-200ml-netmeds.jpg",
  "digene acidity relief gel mint (200ml)": "/medicines/digene-acidity-relief-gel-mint-200ml-netmeds.jpg",
  "digene acidity relief gel mint": "/medicines/digene-acidity-relief-gel-mint-200ml-netmeds.jpg",
  "digene": "/medicines/digene-acidity-relief-gel-mint-200ml-netmeds.jpg",
  "gelusil mps liquid antacid mint (200ml)": "/medicines/gelusil-mps-liquid-antacid-mint-200ml-netmeds.jpg",
  "gelusil mps liquid antacid mint": "/medicines/gelusil-mps-liquid-antacid-mint-200ml-netmeds.jpg",
  "gelusil": "/medicines/gelusil-mps-liquid-antacid-mint-200ml-netmeds.jpg",
  "digene chewable tablet mint (strip of 15)": "/medicines/digene-chewable-tablet-mint-strip-of-15-netmeds.jpg",
  "digene chewable tablet mint": "/medicines/digene-chewable-tablet-mint-strip-of-15-netmeds.jpg",
  "eno fruit salt regular (5g sachet)": "/medicines/eno-fruit-salt-regular-5g-sachet-netmeds.jpg",
  "eno fruit salt regular": "/medicines/eno-fruit-salt-regular-5g-sachet-netmeds.jpg",
  "eno": "/medicines/eno-fruit-salt-regular-5g-sachet-netmeds.jpg",
  "duphalac oral solution (150ml)": "/medicines/duphalac-oral-solution-150ml-netmeds.jpg",
  "duphalac oral solution": "/medicines/duphalac-oral-solution-150ml-netmeds.jpg",
  "duphalac": "/medicines/duphalac-oral-solution-150ml-netmeds.jpg",
  "dulcolax 5mg tablet": "/medicines/dulcolax-5mg-tablet-netmeds.jpg",
  "dulcolax": "/medicines/dulcolax-5mg-tablet-netmeds.jpg",
  "softovac bowel regulator (100g)": "/medicines/softovac-bowel-regulator-100g-netmeds.jpg",
  "softovac bowel regulator": "/medicines/softovac-bowel-regulator-100g-netmeds.jpg",
  "softovac": "/medicines/softovac-bowel-regulator-100g-netmeds.jpg",
  "lopamide 2mg capsule": "/medicines/lopamide-2mg-capsule-netmeds.jpg",
  "lopamide": "/medicines/lopamide-2mg-capsule-netmeds.jpg",
  "redotil 100mg capsule": "/medicines/redotil-100mg-capsule-netmeds.jpg",
  "redotil": "/medicines/redotil-100mg-capsule-netmeds.jpg",
  "cetzine 10mg tablet": "/medicines/cetzine-10mg-tablet-netmeds.jpg",
  "cetzine": "/medicines/cetzine-10mg-tablet-netmeds.jpg",
  "levocet 5mg tablet": "/medicines/levocet-5mg-tablet-netmeds.jpg",
  "levocet": "/medicines/levocet-5mg-tablet-netmeds.jpg",
  "montair-lc tablet": "/medicines/montair-lc-tablet-netmeds.jpg",
  "montair": "/medicines/montair-lc-tablet-netmeds.jpg",
  "allegra 120mg tablet": "/medicines/allegra-120mg-tablet-netmeds.jpg",
  "allegra": "/medicines/allegra-120mg-tablet-netmeds.jpg",
  "avil 25mg tablet": "/medicines/avil-25mg-tablet-netmeds.jpg",
  "avil": "/medicines/avil-25mg-tablet-netmeds.jpg",
  "caladryl calamine lotion (120ml)": "/medicines/caladryl-calamine-lotion-120ml-netmeds.jpg",
  "caladryl calamine lotion": "/medicines/caladryl-calamine-lotion-120ml-netmeds.jpg",
  "caladryl": "/medicines/caladryl-calamine-lotion-120ml-netmeds.jpg",
  "asthalin 100mcg inhaler": "/medicines/asthalin-100mcg-inhaler-netmeds.jpg",
  "asthalin": "/medicines/asthalin-100mcg-inhaler-netmeds.jpg",
  "budecort 200mcg inhaler": "/medicines/budecort-200mcg-inhaler-netmeds.jpg",
  "budecort": "/medicines/budecort-200mcg-inhaler-netmeds.jpg",
  "foracort 200 inhaler": "/medicines/foracort-200-inhaler-netmeds.jpg",
  "foracort": "/medicines/foracort-200-inhaler-netmeds.jpg",
  "ascoril ls syrup (100ml)": "/medicines/ascoril-ls-syrup-100ml-netmeds.jpg",
  "ascoril ls syrup": "/medicines/ascoril-ls-syrup-100ml-netmeds.jpg",
  "ascoril": "/medicines/ascoril-ls-syrup-100ml-netmeds.jpg",
  "ascoril d plus syrup (100ml)": "/medicines/ascoril-d-plus-syrup-100ml-netmeds.jpg",
  "ascoril d plus syrup": "/medicines/ascoril-d-plus-syrup-100ml-netmeds.jpg",
  "benadryl cough formula syrup (150ml)": "/medicines/benadryl-cough-formula-syrup-150ml-netmeds.jpg",
  "benadryl cough formula syrup": "/medicines/benadryl-cough-formula-syrup-150ml-netmeds.jpg",
  "benadryl": "/medicines/benadryl-cough-formula-syrup-150ml-netmeds.jpg",
  "glycomet 500mg sr tablet": "/medicines/glycomet-500mg-sr-tablet-netmeds.jpg",
  "glycomet": "/medicines/glycomet-500mg-sr-tablet-netmeds.jpg",
  "glycomet-gp 1 tablet": "/medicines/glycomet-gp-1-tablet-netmeds.jpg",
  "glycomet-gp": "/medicines/glycomet-gp-1-tablet-netmeds.jpg",
  "glycomet-gp 2 tablet": "/medicines/glycomet-gp-2-tablet-netmeds.jpg",
  "janumet 50mg/500mg tablet": "/medicines/janumet-50mg-500mg-tablet-netmeds.jpg",
  "janumet": "/medicines/janumet-50mg-500mg-tablet-netmeds.jpg",
  "tenlimac 20mg tablet": "/medicines/tenlimac-20mg-tablet-netmeds.jpg",
  "tenlimac": "/medicines/tenlimac-20mg-tablet-netmeds.jpg",
  "forxiga 10mg tablet": "/medicines/forxiga-10mg-tablet-netmeds.jpg",
  "forxiga": "/medicines/forxiga-10mg-tablet-netmeds.jpg",
  "human mixtard 30/70 100iu/ml injection": "/medicines/human-mixtard-30-70-injection.png",
  "human mixtard": "/medicines/human-mixtard-30-70-injection.png",
  "telma 40mg tablet": "/medicines/telma-40mg-tablet-netmeds.jpg",
  "telma": "/medicines/telma-40mg-tablet-netmeds.jpg",
  "telma-am tablet": "/medicines/telma-am-tablet-netmeds.jpg",
  "amlong 5mg tablet": "/medicines/amlong-5mg-tablet-netmeds.jpg",
  "amlong": "/medicines/amlong-5mg-tablet-netmeds.jpg",
  "atorva 20mg tablet": "/medicines/atorva-20mg-tablet-netmeds.jpg",
  "atorva": "/medicines/atorva-20mg-tablet-netmeds.jpg",
  "rosuvas 10mg tablet": "/medicines/rosuvas-10mg-tablet-netmeds.jpg",
  "rosuvas": "/medicines/rosuvas-10mg-tablet-netmeds.jpg",
  "ecosprin 75mg tablet": "/medicines/ecosprin-75mg-tablet-netmeds.jpg",
  "ecosprin": "/medicines/ecosprin-75mg-tablet-netmeds.jpg",
  "deplatt 75mg tablet": "/medicines/deplatt-75mg-tablet-netmeds.jpg",
  "deplatt": "/medicines/deplatt-75mg-tablet-netmeds.jpg",
  "cardace 5mg tablet": "/medicines/cardace-5mg-tablet-netmeds.jpg",
  "cardace": "/medicines/cardace-5mg-tablet-netmeds.jpg",
  "sorbitrate 5mg sublingual tablet": "/medicines/sorbitrate-5mg-sublingual-tablet-netmeds.jpg",
  "sorbitrate": "/medicines/sorbitrate-5mg-sublingual-tablet-netmeds.jpg",
  "candid 1% cream (20g)": "/medicines/candid-1-cream-20g-netmeds.jpg",
  "candid 1% cream": "/medicines/candid-1-cream-20g-netmeds.jpg",
  "candid": "/medicines/candid-1-cream-20g-netmeds.jpg",
  "candid dusting powder (100g)": "/medicines/candid-dusting-powder-100g-netmeds.jpg",
  "candid dusting powder": "/medicines/candid-dusting-powder-100g-netmeds.jpg",
  "t-bact 2% ointment (5g)": "/medicines/t-bact-2-ointment-5g-netmeds.jpg",
  "t-bact 2% ointment": "/medicines/t-bact-2-ointment-5g-netmeds.jpg",
  "t-bact": "/medicines/t-bact-2-ointment-5g-netmeds.jpg",
  "fucidin 2% cream (10g)": "/medicines/fucidin-2-cream-10g-netmeds.jpg",
  "fucidin 2% cream": "/medicines/fucidin-2-cream-10g-netmeds.jpg",
  "fucidin": "/medicines/fucidin-2-cream-10g-netmeds.jpg",
  "permite 5% w/w cream (60g)": "/medicines/permite-5-w-w-cream-60g-netmeds.jpg",
  "permite 5% w/w cream": "/medicines/permite-5-w-w-cream-60g-netmeds.jpg",
  "permite": "/medicines/permite-5-w-w-cream-60g-netmeds.jpg",
  "betadine 10% microbicidal ointment (20g)": "/medicines/betadine-10-microbicidal-ointment-20g-netmeds.jpg",
  "betadine 10% microbicidal ointment": "/medicines/betadine-10-microbicidal-ointment-20g-netmeds.jpg",
  "betadine": "/medicines/betadine-10-microbicidal-ointment-20g-netmeds.jpg",
  "betadine 5% antiseptic solution (100ml)": "/medicines/betadine-5-antiseptic-solution-100ml-netmeds.jpg",
  "betadine 5% antiseptic solution": "/medicines/betadine-5-antiseptic-solution-100ml-netmeds.jpg",
  "dettol antiseptic liquid (250ml)": "/medicines/dettol-antiseptic-liquid-250ml-netmeds.jpg",
  "dettol antiseptic liquid": "/medicines/dettol-antiseptic-liquid-250ml-netmeds.jpg",
  "dettol": "/medicines/dettol-antiseptic-liquid-250ml-netmeds.jpg",
  "burnol antiseptic burn cream (20g)": "/medicines/burnol-antiseptic-burn-cream-20g-netmeds.jpg",
  "burnol antiseptic burn cream": "/medicines/burnol-antiseptic-burn-cream-20g-netmeds.jpg",
  "burnol": "/medicines/burnol-antiseptic-burn-cream-20g-netmeds.jpg",
  "hansaplast regular bandage strips (pack of 20)": "/medicines/hansaplast-regular-bandage-strips-pack-of-20-netmeds.jpg",
  "hansaplast regular bandage strips": "/medicines/hansaplast-regular-bandage-strips-pack-of-20-netmeds.jpg",
  "hansaplast": "/medicines/hansaplast-regular-bandage-strips-pack-of-20-netmeds.jpg",
  "refresh tears 0.5% eye drops (10ml)": "/medicines/refresh-tears-0-5-eye-drops-10ml-netmeds.jpg",
  "refresh tears 0.5% eye drops": "/medicines/refresh-tears-0-5-eye-drops-10ml-netmeds.jpg",
  "refresh tears": "/medicines/refresh-tears-0-5-eye-drops-10ml-netmeds.jpg",
  "ciplox 0.3% eye/ear drops (10ml)": "/medicines/ciplox-0-3-eye-ear-drops-10ml-netmeds.jpg",
  "ciplox 0.3% eye/ear drops": "/medicines/ciplox-0-3-eye-ear-drops-10ml-netmeds.jpg",
  "ciplox": "/medicines/ciplox-0-3-eye-ear-drops-10ml-netmeds.jpg",
  "clearwax ear drops (10ml)": "/medicines/clearwax-ear-drops-10ml-netmeds.jpg",
  "clearwax ear drops": "/medicines/clearwax-ear-drops-10ml-netmeds.jpg",
  "clearwax": "/medicines/clearwax-ear-drops-10ml-netmeds.jpg",
  "otrivin oxy fast relief nasal spray (10ml)": "/medicines/otrivin-oxy-fast-relief-nasal-spray-10ml-netmeds.jpg",
  "otrivin oxy fast relief nasal spray": "/medicines/otrivin-oxy-fast-relief-nasal-spray-10ml-netmeds.jpg",
  "otrivin": "/medicines/otrivin-oxy-fast-relief-nasal-spray-10ml-netmeds.jpg",
  "nasoclear saline nasal spray (20ml)": "/medicines/nasoclear-saline-nasal-spray-20ml-netmeds.jpg",
  "nasoclear saline nasal spray": "/medicines/nasoclear-saline-nasal-spray-20ml-netmeds.jpg",
  "nasoclear": "/medicines/nasoclear-saline-nasal-spray-20ml-netmeds.jpg",
  "calcirol 60,000 iu cholecalciferol sachet": "/medicines/calcirol-60-000-iu-cholecalciferol-sachet-netmeds.jpg",
  "calcirol": "/medicines/calcirol-60-000-iu-cholecalciferol-sachet-netmeds.jpg",
  "uprise-d3 60k softgel capsule": "/medicines/uprise-d3-60k-softgel-capsule-netmeds.jpg",
  "uprise-d3": "/medicines/uprise-d3-60k-softgel-capsule-netmeds.jpg",
  "becosules z capsule": "/medicines/becosules-z-capsule-netmeds.jpg",
  "becosules": "/medicines/becosules-z-capsule-netmeds.jpg",
  "limcee 500mg chewable tablet": "/medicines/limcee-500mg-chewable-tablet-netmeds.jpg",
  "limcee": "/medicines/limcee-500mg-chewable-tablet-netmeds.jpg",
  "orofer-xt tablet": "/medicines/orofer-xt-tablet-netmeds.jpg",
  "orofer": "/medicines/orofer-xt-tablet-netmeds.jpg",
  "folvite 5mg tablet": "/medicines/folvite-5mg-tablet-netmeds.jpg",
  "folvite": "/medicines/folvite-5mg-tablet-netmeds.jpg",
  "neurobion forte tablet": "/medicines/neurobion-forte-tablet-netmeds.jpg",
  "neurobion": "/medicines/neurobion-forte-tablet-netmeds.jpg",
  "shelcal 500 tablet": "/medicines/shelcal-500-tablet-netmeds.jpg",
  "shelcal": "/medicines/shelcal-500-tablet-netmeds.jpg",
  "caldikind plus capsule": "/medicines/caldikind-plus-capsule-netmeds.jpg",
  "caldikind": "/medicines/caldikind-plus-capsule-netmeds.jpg",
  "cartigen 1500mg tablet": "/medicines/cartigen-1500mg-tablet-netmeds.jpg",
  "cartigen": "/medicines/cartigen-1500mg-tablet-netmeds.jpg",
  "whisper choice regular sanitary pads (6 pads)": "/medicines/whisper-choice-regular-pads.png",
  "whisper choice regular sanitary pads": "/medicines/whisper-choice-regular-pads.png",
  "whisper choice": "/medicines/whisper-choice-regular-pads.png",
  "whisper ultra clean sanitary pads xl (15 pads)": "/medicines/whisper-ultra-xl-pads.png",
  "whisper ultra clean sanitary pads xl": "/medicines/whisper-ultra-clean-sanitary-pads.png",
  "whisper ultra": "/medicines/whisper-ultra-xl-pads.png",
  "o.b. procomfort regular tampons (10 tampons)": "/medicines/ob-tampons-regular.png",
  "o.b. procomfort regular tampons": "/medicines/ob-tampons-regular.png",
  "o.b.": "/medicines/ob-tampons-regular.png",
  "sirona reusable menstrual cup (medium)": "/medicines/sirona-menstrual-cup.png",
  "sirona reusable menstrual cup": "/medicines/sirona-menstrual-cup.png",
  "sirona": "/medicines/sirona-menstrual-cup.png",
  "vwash plus intimate hygiene wash (200ml)": "/medicines/vwash-plus-intimate-hygiene-wash-200ml-netmeds.jpg",
  "vwash plus intimate hygiene wash": "/medicines/vwash-plus-intimate-hygiene-wash-200ml-netmeds.jpg",
  "vwash": "/medicines/vwash-plus-intimate-hygiene-wash-200ml-netmeds.jpg",
  "nua cramp comfort heat patches (3 patches)": "/medicines/nua-heat-patch.png",
  "nua cramp comfort heat patches": "/medicines/nua-heat-patch.png",
  "nua": "/medicines/nua-heat-patch.png",
  "sirona disposable sanitary bags (15 bags)": "/medicines/sirona-disposal-bags.png",
  "sirona disposable sanitary bags": "/medicines/sirona-disposal-bags.png",
  "trapic-mf tablet": "/medicines/trapic-mf-tablet-netmeds.jpg",
  "trapic": "/medicines/trapic-mf-tablet-netmeds.jpg",
  "calpol 250mg peadiatric suspension (60ml)": "/medicines/calpol-250mg-peadiatric-suspension-60ml-netmeds.jpg",
  "calpol 250mg peadiatric suspension": "/medicines/calpol-250mg-peadiatric-suspension-60ml-netmeds.jpg",
  "calpol 100mg/ml infant drops (15ml)": "/medicines/calpol-100mg-ml-infant-drops-15ml-netmeds.jpg",
  "calpol 100mg/ml infant drops": "/medicines/calpol-100mg-ml-infant-drops-15ml-netmeds.jpg",
  "domstal baby oral drops (30ml)": "/medicines/domstal-baby-oral-drops-30ml-netmeds.jpg",
  "domstal baby oral drops": "/medicines/domstal-baby-oral-drops-30ml-netmeds.jpg",
  "domstal": "/medicines/domstal-baby-oral-drops-30ml-netmeds.jpg",
  "augmentin duo dry syrup (30ml)": "/medicines/augmentin-duo-dry-syrup-30ml-netmeds.jpg",
  "augmentin duo dry syrup": "/medicines/augmentin-duo-dry-syrup-30ml-netmeds.jpg",
  "augmentin": "/medicines/augmentin-duo-dry-syrup-30ml-netmeds.jpg",
  "maxtra oral drops (15ml)": "/medicines/maxtra-oral-drops-15ml-netmeds.jpg",
  "maxtra oral drops": "/medicines/maxtra-oral-drops-15ml-netmeds.jpg",
  "maxtra": "/medicines/maxtra-oral-drops-15ml-netmeds.jpg",
  "nasoclear paediatric nasal drops (15ml)": "/medicines/nasoclear-paediatric-nasal-drops-15ml-netmeds.jpg",
  "nasoclear paediatric nasal drops": "/medicines/nasoclear-paediatric-nasal-drops-15ml-netmeds.jpg",
  "augmentin 625 duo tablet": "/medicines/augmentin-625-duo-tablet-netmeds.jpg",
  "azithral 500mg tablet": "/medicines/azithral-500mg-tablet-netmeds.jpg",
  "azithral": "/medicines/azithral-500mg-tablet-netmeds.jpg",
  "taxim-o 200mg tablet": "/medicines/taxim-o-200mg-tablet-netmeds.jpg",
  "taxim-o": "/medicines/taxim-o-200mg-tablet-netmeds.jpg",
  "ciplox 500mg tablet": "/medicines/ciplox-500mg-tablet-netmeds.jpg",
  "flagyl 400mg tablet": "/medicines/flagyl-400mg-tablet-netmeds.jpg",
  "flagyl": "/medicines/flagyl-400mg-tablet-netmeds.jpg",
  "zenflox-oz tablet": "/medicines/zenflox-oz-tablet-netmeds.jpg",
  "zenflox": "/medicines/zenflox-oz-tablet-netmeds.jpg",
  "drotin ds 80mg tablet": "/medicines/drotin-ds-80mg-tablet-netmeds.jpg",
  "drotin": "/medicines/drotin-ds-80mg-tablet-netmeds.jpg",
  "meftal spas tablet": "/medicines/meftal-spas-tablet-netmeds.jpg",
  "meftal": "/medicines/meftal-spas-tablet-netmeds.jpg",
  "whisper ultra clean sanitary pads xl (30 pads)": "/medicines/whisper-ultra-clean-sanitary-pads.png",
  "whisper": "/medicines/whisper-ultra-clean-sanitary-pads.png",
  "sanitary pads – regular (whisper choice)": "/medicines/whisper-choice-regular-pads.png",
  "sanitary pads – regular": "/medicines/whisper-choice-regular-pads.png",
  "sanitary pads – xl (whisper ultra clean)": "/medicines/whisper-ultra-xl-pads.png",
  "sanitary pads – xl": "/medicines/whisper-ultra-xl-pads.png",
  "tampons (o.b. procomfort regular)": "/medicines/ob-tampons-regular.png",
  "tampons": "/medicines/ob-tampons-regular.png",
  "menstrual cup (sirona reusable medium)": "/medicines/sirona-menstrual-cup.png",
  "menstrual cup": "/medicines/sirona-menstrual-cup.png",
  "heating pad / hot water bottle (flamingo)": "/medicines/flamingo-heating-pad.png",
  "heating pad / hot water bottle": "/medicines/flamingo-heating-pad.png",
  "flamingo": "/medicines/flamingo-heating-pad.png",
  "heat patch (nua cramp comfort 3 patches)": "/medicines/nua-heat-patch.png",
  "heat patch": "/medicines/nua-heat-patch.png",
  "unscented wet wipes (himalaya gentle 72s)": "/medicines/himalaya-wet-wipes.png",
  "unscented wet wipes": "/medicines/himalaya-wet-wipes.png",
  "himalaya": "/medicines/himalaya-wet-wipes.png",
  "tissues (paseo soft facial tissue box)": "/medicines/paseo-facial-tissues.png",
  "tissues": "/medicines/paseo-facial-tissues.png",
  "paseo": "/medicines/paseo-facial-tissues.png",
  "disposable sanitary-waste bags (sirona 15s)": "/medicines/sirona-disposal-bags.png",
  "disposable sanitary-waste bags": "/medicines/sirona-disposal-bags.png",
  "hand sanitizer (dettol instant 100ml)": "/medicines/dettol-hand-sanitizer.png",
  "hand sanitizer": "/medicines/dettol-hand-sanitizer.png"
};

/**
 * Returns the exact unique realistic product photo URL for any medicine object or string.
 * @param {Object|string} medicine - Medicine object or medicine name
 * @returns {string} Image path
 */
export function getMedicineImage(medicine) {
  if (!medicine) return '/medicines/dolo-650mg-tablet-netmeds.jpg';

  const medicineObj = typeof medicine === 'object' ? medicine : { name: medicine };
  const rawName = (medicineObj.name || medicineObj.title || '').trim();
  const normalized = rawName.toLowerCase().replace(/\s+/g, ' ');

  // 1. Direct match in MEDICINE_IMAGE_MAP
  if (MEDICINE_IMAGE_MAP[normalized]) {
    return MEDICINE_IMAGE_MAP[normalized];
  }

  // 2. Partial / Key Match (sorted by length descending for best specificity)
  const keys = Object.keys(MEDICINE_IMAGE_MAP).sort((a, b) => b.length - a.length);
  for (const key of keys) {
    if (normalized.startsWith(key) || key.startsWith(normalized) || normalized.includes(key)) {
      return MEDICINE_IMAGE_MAP[key];
    }
  }

  // 3. Fallback to valid medicine object image if specified
  if (medicineObj.image && (medicineObj.image.startsWith('/medicines/') && !medicineObj.image.endsWith('.svg'))) {
    return medicineObj.image;
  }

  return '/medicines/dolo-650mg-tablet-netmeds.jpg';
}

export default getMedicineImage;
